name: Generate system calls HTML table

on:
  workflow_dispatch:
  push:
    branches: 
    - "master"
    paths:
    - "data/*"
  workflow_run:
    workflows: ["Update system calls data"]
    types:
      - completed


jobs:
  generate-and-deploy:
    permissions:
      contents: read
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout syscalls-table
        uses: actions/checkout@v4
        with:
          path: syscalls-table/
          ref: master
          submodules: true

      - name: Create Python virtualenv
        working-directory: syscalls-table/
        run: |
          python3 -m venv /tmp/venv
          . /tmp/venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install 'system calls' package
        working-directory: syscalls-table/
        run: |
          python3 -m pip install --upgrade pip
          pip install .

      - name: Generate system calls HTML
        working-directory: syscalls-table/
        run: |
          mkdir -p out
          pip list
          python -c "import system_calls; print(system_calls)"
          python -c "from system_calls import cli; print(cli)"
          python3 examples/generate-html-table.py > out/syscalls.html
